/**
 * @file tick_file_reader.hpp
 * @brief Zero-copy binary tick file reader backed by mmap.
 *
 * Opens a tick data file (generated by generate_ticks), validates the header,
 * and provides direct pointer access to the tick array via mmap. No parsing,
 * no copying — the OS page cache serves as the read buffer.
 *
 * HFT context:
 *   mmap-based file reading is the standard pattern for market data replay
 *   and backtesting. Benefits over read():
 *     - Zero copy: data stays in page cache, no kernel → userspace copy.
 *     - Lazy loading: only pages actually accessed are paged in.
 *     - OS handles prefetching (sequential readahead heuristic).
 *
 * Usage:
 *   auto reader = TickFileReader::open("market_data.bin");
 *   if (!reader) { return 1; }
 *   for (const auto& tick : reader->ticks()) {
 *       // publish tick...
 *   }
 */

#pragma once

#include "shared/tick_data.hpp"
#include "sys/log/signal_logger.hpp"
#include "sys/memory/mmap_region.hpp"

#include <cassert>
#include <cstddef>
#include <cstdint>
#include <fcntl.h>
#include <optional>
#include <span>
#include <unistd.h>

namespace mk::app {

class TickFileReader {
public:
  /// Open and validate a tick data file.
  /// @return std::nullopt on failure (file not found, invalid format, etc.).
  [[nodiscard]] static std::optional<TickFileReader>
  open(const char *path) noexcept {
    // Open file read-only.
    // NOLINTNEXTLINE(*-vararg)
    const int fd = ::open(path, O_RDONLY | O_CLOEXEC);
    if (fd == -1) {
      sys::log::signal_log("[REPLAY] Failed to open: ", path, '\n');
      return std::nullopt;
    }

    // mmap the entire file read-only. MmapRegion::map_file auto-detects size.
    auto region = sys::memory::MmapRegion::map_file(fd, false);
    ::close(fd);

    if (!region) {
      sys::log::signal_log("[REPLAY] Failed to mmap: ", path, '\n');
      return std::nullopt;
    }

    // Validate minimum size for header.
    if (region->size() < sizeof(TickFileHeader)) {
      sys::log::signal_log("[REPLAY] File too small for header\n");
      return std::nullopt;
    }

    const auto *header =
        reinterpret_cast<const TickFileHeader *>(region->data());

    // Validate magic.
    if (header->magic != kTickFileMagic) {
      sys::log::signal_log("[REPLAY] Invalid file magic\n");
      return std::nullopt;
    }

    // Validate version.
    if (header->version != kTickFileVersion) {
      sys::log::signal_log("[REPLAY] Unsupported version: ", header->version,
                           '\n');
      return std::nullopt;
    }

    // Validate file size matches tick count.
    const std::size_t expected = tick_file_size(header->tick_count);
    if (region->size() < expected) {
      sys::log::signal_log("[REPLAY] File truncated: expected ", expected,
                           " bytes, got ", region->size(), '\n');
      return std::nullopt;
    }

    sys::log::signal_log("[REPLAY] Loaded: ", header->tick_count, " ticks, ",
                         header->symbol_count, " symbols\n");

    return TickFileReader(std::move(*region));
  }

  // -- Observers --

  [[nodiscard]] const TickFileHeader &header() const noexcept {
    return *header_;
  }
  [[nodiscard]] std::uint64_t tick_count() const noexcept {
    return header_->tick_count;
  }
  [[nodiscard]] std::uint32_t symbol_count() const noexcept {
    return header_->symbol_count;
  }

  [[nodiscard]] const Tick &tick(std::size_t index) const noexcept {
    assert(index < header_->tick_count);
    return ticks_[index];
  }

  [[nodiscard]] std::span<const Tick> ticks() const noexcept {
    return {ticks_, static_cast<std::size_t>(header_->tick_count)};
  }

private:
  explicit TickFileReader(sys::memory::MmapRegion region) noexcept
      : region_(std::move(region)) {
    const auto *base = static_cast<const std::byte *>(region_.data());
    header_ = reinterpret_cast<const TickFileHeader *>(base);
    ticks_ = reinterpret_cast<const Tick *>(base + sizeof(TickFileHeader));
  }

  sys::memory::MmapRegion region_;
  const TickFileHeader *header_ = nullptr;
  const Tick *ticks_ = nullptr;
};

} // namespace mk::app
