/**
 * @file strategy_policy.hpp
 * @brief StrategyPolicy concept, Signal type, and pipeline-wide strategy constants.
 *
 * Defines the compile-time interface any trading strategy must satisfy to plug
 * into the tick-to-trade pipeline. The event loop is templated on StrategyPolicy
 * — compile-time polymorphism, no vtable.
 *
 * Why template policy instead of virtual interface:
 *   HFT hot paths avoid virtual dispatch (~1-2ns vtable lookup per call).
 *   Template instantiation resolves the strategy at compile time, enabling
 *   full inlining of on_market_data() into the event loop. The trade-off:
 *   strategy selection is compile-time only (rebuild to switch strategies).
 *   This is acceptable — production HFT systems deploy per-strategy binaries.
 *
 * Concrete implementations: see spread_strategy.hpp.
 */

#pragma once

#include "shared/protocol.hpp" // MarketDataUpdate, algo::Side/Price/Qty

#include <concepts>
#include <cstdint>

namespace mk::app {

/// Trading signal generated by the strategy.
struct Signal {
  algo::Side side{};
  algo::Price price{0};
  algo::Qty qty{0};
  std::uint32_t symbol_id{0}; // Which instrument triggered this signal
};

/// Compile-time interface for trading strategies plugged into the pipeline.
/// Any type satisfying this concept can be used as the strategy template
/// parameter in run_event_loop() — no virtual dispatch, full inlining.
template <typename T>
concept StrategyPolicy = requires(T t, const MarketDataUpdate &u, Signal &out) {
  // kMaxSymbols: compile-time symbol universe size.
  // Used by the pipeline to size StrategyCtx buffers and validate symbol IDs.
  // Each concrete strategy declares its own capacity via this static member.
  { T::kMaxSymbols } -> std::convertible_to<std::uint32_t>;
  { t.on_market_data(u, out) } -> std::same_as<bool>;
  { t.signals_generated() } -> std::convertible_to<std::uint64_t>;
};

} // namespace mk::app
